### ISSUE TITLE
@ViewChild

### ISSUE THREAD

**Issue by tycho01** [shuhei/babel-plugin-angular2-annotations#18]
I just managed to convert all my TS to JS using your plugin, except for one @ViewChild line, which works for TS but seems to fail conversion. Normally this annotation can take either a class or a string parameter, but either seem to fail somehow.

My minimum reproducable case is like this:

```
import { Component, ViewChild } from 'angular2/core';
@Component({
  selector: 'foo',
  template: `<p #x>foo</p>`,
})
export class Foo {
  @ViewChild('x') comp;
  constructor() {}
}
```

I wonder if something is up on my side, or if something might be up with conversion. Your implementation seems general enough I wouldn't expect it to fail for specific cases like this -- I'm just confused that only this part failed for me. Does it work for you?

Error statement, with plugin info but otherwise non-descriptive:

```
Module parse failed: ...\node_modules\babel-loader\index.js?{"cacheDirectory":true,"plugins":["syntax-async-functions","transform-regenerator","transform-runtime","add-module-exports","transform-decorators-legacy","angular2-annotations","transform-class-properties","transform-flow-strip-types"],"presets":["es2015","stage-1","stage-0"]}!...\foo.js Line 3: Unexpected token
You may need an appropriate loader to handle this file type.
| 'use strict';
|
| import _Object$defineProperty from 'babel-runtime/core-js/object/define-property';
|
| var _dec, _dec2, _class, _desc, _value, _class2, _descriptor;
```

**Comment by shuhei** [comment]
Hi @tycho01, may I see your minimum build config, such as webpack config and .babelrc, so that I can reproduce and investigate it?

**Comment by shuhei** [comment]
Also, I'd like to see versions of used npm modules.

**Comment by tycho01** [comment]
Thank you; after investigating more I commented a line from [babel-plugin-transform-runtime](https://phabricator.babeljs.io/T2877), fixing the syntax error. Somehow I'm still getting a mysterious runtime error, presumably from the same line, but I think I'll need to further look into that by comparing transpiled output first. Until further indication this package might be related let's considered this closed.
