### ISSUE TITLE
Constructor setter support?

### ISSUE THREAD

**Issue by amcdnl** [shuhei/babel-plugin-angular2-annotations#23]
I think one of my favorite things in typescript is the ability to do something like:

```
@Component({ /* ... */ })
class HelloComponent {
  constructor(private ngZone: NgZone) { }
}
```

and `ngZone` be on the scope of the `HelloComponent`. Any thoughts on this?

**Comment by shuhei** [comment]
It might be handy but this is not a repo that supports everthing TypeScript has.

**Comment by shuhei** [comment]
Something like [this](https://github.com/shuhei/babel-plugin-auto-assign) might work. I haven't maintained it though.

**Comment by amcdnl** [comment]
@shuhei I agree, not trying to reproduce typescript but I thought it was kinda along the same lines as the constructor annotations.
