### ISSUE TITLE
Upgrade angular dependencies

### ISSUE THREAD

**Issue by CarreraPHP** [shuhei/babel-plugin-angular2-annotations#28]
Upgrade angular dependencies from 2.1.1 to latest

**Comment by shuhei** [comment]
Fixed by https://github.com/shuhei/babel-plugin-angular2-annotations/commit/5351c75b57f628e2c5aa5458116e749196cfaa4a. BTW, this package doesn't depend on angular at all. Angular packages are used only for testing.
