### ISSUE TITLE
Type Annotations for Constructor Parameters don't Work

### ISSUE THREAD

**Issue by ahmehri** [shuhei/babel-plugin-angular2-annotations#30]
Type annotations for constructor parameters don't work because babylon cannot parse them. I get the following error:
`SyntaxError: <file name>: Unexpected token, expected ,`

This is because of babel/babel#3204.

README should be updated to clarify this change.

**Comment by shuhei** [comment]
Thanks for reporting. Now it should work because bablylon started parsing param decorators without patching. I'll take a look later.
