### ISSUE TITLE
webpack integration 

### ISSUE THREAD

**Issue by dennis-b** [shuhei/babel-plugin-angular2-annotations#5]
hi

Is there a way to use this plugin with webpack ?

best regards
dennis

**Comment by shuhei** [comment]
@dennis-b Yes! You can use webpack [babel-loader](https://github.com/babel/babel-loader) with this plugin.

You need to tell babel to use this plugin. There are some ways to do so. [babel-loader can take options](https://github.com/babel/babel-loader#options) but I recommend you to create a file called [`.babelrc`](https://babeljs.io/docs/usage/babelrc/) with the following content.

```
{
  "plugins": ["angular2-annotations"]
}
```

**Comment by dennis-b** [comment]
Thanks this helped me a lot.
