### ISSUE TITLE
Update to Babel 6.0

### ISSUE THREAD

**Issue by shuhei** [shuhei/babel-plugin-angular2-annotations#6]

**Comment by gdi2290** [comment]
:+1:

**Comment by shuhei** [comment]
Still sending patches to Babel itself to make it work...

- https://github.com/babel/babel/pull/2696
- https://github.com/babel/babel/pull/2697

**Comment by gutenye** [comment]
:+1:

**Comment by Swiip** [comment]
:+1:

**Comment by shuhei** [comment]
I cannot upgrade to Babel 6 until Babel 6 implements decorators again. Its decorators don't work right now.

Please see #7 for more details.

**Comment by shanestillwell** [comment]
Would including this plugin work for making Babel transform decorators?
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-decorators

**Comment by shuhei** [comment]
@shanestillwell No, [it doesn't work correctly](https://phabricator.babeljs.io/T2645#65806).

Some folks re-implemented Babel 5 decorators as a Babel 6 plugin. It should work. I'm gonna try it this month. https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy

**Comment by amcdnl** [comment]
@shuhei FYI - I tried it w/ legacy decorators and your babel6 PR code, does not work :( . http://www.screencast.com/t/XdEAKf6FhdB

**Comment by shuhei** [comment]
@amcdnl Thanks for trying! Probably I'll be able to take a look at it this weekend...

**Comment by shuhei** [comment]
Thanks guys, now upgraded to Babel 6!

**Comment by gdi2290** [comment]
:+1:
