### ISSUE TITLE
Issue in Babel-Angular2-App

### ISSUE THREAD

**Issue by jgodi** [shuhei/babel-plugin-angular2-annotations#9]
I forked the demo application and attempted to convert that over to Babel 6 for a good example. You can see the code here: https://github.com/jgodi/babel-angular2-app.

I am running into some issues when trying to build the application:

```bash
jgodi:babel-angular2-app jgodi$ gulp build
[08:18:19] Requiring external module babel-core/register
[08:18:19] Using gulpfile ~/github/babel-angular2-app/gulpfile.babel.js
[08:18:19] Starting 'copy'...
[08:18:19] Finished 'copy' after 18 ms
[08:18:19] Starting 'build'...
TypeError in plugin 'browserify'
Message:
    /Users/jgodi/github/babel-angular2-app/src/app.js: Cannot convert undefined or null to object while parsing file: /Users/jgodi/github/babel-angular2-app/src/app.js
Details:
    _babel: true
    filename: /Users/jgodi/github/babel-angular2-app/src/app.js
    stream: [object Object]
```

This is with the following dependencies added/updated:

```json
  "babel": "6.3.13",
  "babel-core": "6.3.17",
  "babel-eslint": "^5.0.0-beta6",
  "babel-plugin-angular2-annotations": "^3.0.3",
  "babel-plugin-transform-decorators-legacy": "^1.3.3",
  "babel-plugin-transform-flow-strip-types": "^6.3.15",
  "babel-preset-es2015": "^6.3.13",
  "babelify": "^7.2.0",
  "babylon": "6.3.20",
```

and a `.babelrc` file that looks like this:

```
{
  "presets": ["es2015"],
  "plugins": [
    "angular2-annotations",
    "transform-decorators-legacy",
    "transform-flow-strip-types"
  ]
}
```

Any thoughts? If you want you can pull down my fork and see for yourself too. It would be cool to get the sample application updated and running on this, then I will update it to Angular 2 Beta.0.

Thanks!

**Comment by amcdnl** [comment]
I'm getting this too in my own project: http://www.screencast.com/t/7UGfVOhoRxlJ

**Comment by shuhei** [comment]
@jgodi @amcdnl Thanks for reporting! I also got the same error and couldn't update the sample app. Now it's the weekend. I'll look into the error.

By the way, the sample app was updated to beta.0 with Babel 5. https://github.com/shuhei/babel-angular2-app/pull/20

**Comment by shuhei** [comment]
Ah, the error happens on classes that don't have constructor. I'll fix it soon.
